# Generated by Django 5.2.5 on 2025-09-04 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_address_profile_phone_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('path_backend', 'http_method')},
        ),
    ]
